#' Support function for ingest_wahis_report to find table in report
#' @param page output of read_xml
#' @param pref th = colnames; td = table header ?
#' @param header_name string to match when searching colnames or table headers (can be vector of strings)
#' @importFrom purrr map compact 
#' @noRd
find_parent <- function(page, pref, header_name){
    
    # create search string
    tbl_header_xml <- paste0('//', pref, '[contains(., "',
                             header_name,
                             '")]')
    
    # search page and get parents
    parent <- map(tbl_header_xml, function(x){
        out <-  xml_find_all(page, x) %>%
            xml_parents()
        if(length(out)==0){return(NULL)}
        out
    })
    
    # remove NULL items
    parent <- compact(parent)
    
    # subset parents for html_node table
    parent <- map(parent, function(x){
        x[[which(xml_name(x) == "table")]]
    })
    
    return(parent)
}

#' Support function for ingest_wahis_report to clean html tables
#' @param parents generated by find_parent
#' @importFrom purrr map_df
#' @noRd
clean_oie_report_table <- function(parent){
    
    if(is.null(parent) || length(parent)==0){return()}
    
    map_df(parent, function(p_node){
        p_node %>%
            html_table(fill = TRUE) %>%
            as_tibble() %>%
            set_names(.[2,]) %>%
            clean_names() %>%
            slice(-1:-2) %>%
            mutate_all(~na_if(., ""))
    })
}

#' Support function for ingest_wahis_report to find between dividers in report
#' @param headers search strings
#' @importFrom purrr map compact  
#' @noRd
get_header_index <- function(headers, siblings){
    
    out <- map(headers, function(x){
        p_nodeset <- xml_nodes(siblings, xpath = paste0('//div[contains(text(), "', x, '")]'))
        if(length(p_nodeset)==0){return(NULL)}
        which(siblings %in% p_nodeset) 
    }) 
    
    names(out) <- headers
    compact(out) %>% unlist()
}


#' Support function for ingest_wahis_report to find between dividers in report
#' @param page output of read_xml
#' @param first_header_name string to match when searching colnames or table headers (can be vector of strings)
#' @param second_header_name string to match when searching colnames or table headers (can be vector of strings)
#' @importFrom purrr imap_dfr map_dfr map2
#' @noRd
get_tables_by_index <- function(page, first_header_name, second_header_name){
    
    # all tables
    siblings <-  xml_nodes(page, xpath='//div[@class="ContentBigTable"]/*')
    
    # search page
    first_header_index <- get_header_index(first_header_name, siblings)
    second_header_index <- get_header_index(second_header_name, siblings)
    
    # check that there is data between headers 
    check_index <- second_header_index - first_header_index > 1
    
    first_header_index <- first_header_index[check_index]
    second_header_index <- second_header_index[check_index]
    
    # get all indices
    all_index <- map2(first_header_index, second_header_index, ~(.x+1):(.y-1)) 
    
    # pull data and include oie_listed and taxa
    # thiw might go outside of function to accomodate nonreported illnesses
    imap_dfr(all_index, function(x, y){
        oie_listed <- switch(y, "2. OIE-listed diseases absent in " = TRUE, "6. Non OIE-Listed diseases absent in " = FALSE) 
        tabs <- siblings[x]
        map_dfr(tabs, function(tb){
            clean_oie_report_table(list(tb)) %>%
                fill(disease, .direction = "down") %>%
                mutate(oie_listed = oie_listed,
                       taxa = html_table(tb, fill = TRUE)[1,1])
        })
    })
}


#' Extract Info from WAHIS Annual and Semi-Annual Reports
#'
#' Extract the information found in the Annual and Semi-Annual OIE World Animal Health Information
#' System (WAHIS) HTML reports. These reports have to be provided to this function.
#'
#' @param web_page Name of the downloaded web page
#'
#' @return A list with elements:
#' \item{id}{Record id.}
#' \item{diseases_present}{Table of disease present in country over time period}
#' @examples
#' ##ingest_wahis_report("../data-raw/raw_wahis_reports/BWA_2016_sem0.html")
#' @export
#' @importFrom xml2 read_xml xml_find_first xml_text xml_parents
#' @importFrom stringi stri_extract_first_regex
#' @importFrom stringr str_remove str_trim str_detect str_sub
#' @importFrom rvest html_table
#' @importFrom tidyr fill
#' @importFrom magrittr set_names
#' @importFrom janitor clean_names
#' @importFrom purrr map map2 map_df map_int keep reduce
#' @import dplyr

ingest_wahis_report <- function(web_page) {
    
    # get page
    page <- suppressWarnings(read_xml(web_page, as_html = TRUE, options = c("RECOVER", "NOERROR", 
                                                                            "NOBLANKS")))
    # get country name
    country <- xml_find_first(page, '//td[contains(., "Country:")]') %>% xml_text() %>% stri_extract_first_regex("(?<=:\\s).*")
    
    # return error if country name is NA - indicates that report was not correctly loaded (eg )
    if(is.na(country)){return("report error")}
    
    # get report period
    report_period <- xml_find_first(page, '//td[contains(., "Report period:")]') %>% xml_text() %>% stri_extract_first_regex("(?<=:\\s).*")
    report_year <- str_sub(report_period, start = -4) %>% as.numeric()
    report_months <- str_sub(report_period, end = -6)
    
    # 1 -----------------------------------------------------------------------
    # OIE- and non-OIE-listed diseases/infections present
    # pre-2014 also includes non-OIE-listed diseases present
    
    parent <- find_parent(page, 
                          pref = "td",
                          header_name = c("1. Summary on OIE-listed diseases/infections present in", "5. Summary on non OIE-Listed diseases/infections present in"))
    
    diseases_present <- clean_oie_report_table(parent)
    
    if(!is.null(diseases_present)){ # may be NULL if no diseases were detected
        
        # should only be one or two matches
        assertthat::assert_that(length(parent) <= 2) 
        
        # check that we have the right table
        assertthat::has_name(diseases_present, c("new_outbreaks", "occurrence")) 
        
        # temporarily add non_oie_listed_disease or oie_listed_disease fields
        if(!"non_oie_listed_disease" %in% colnames(diseases_present)){diseases_present$non_oie_listed_disease <- NA_character_}
        if(!"oie_listed_disease" %in% colnames(diseases_present)){diseases_present$oie_listed_disease <- NA_character_}
        
        # light cleaning to format tables identically
        diseases_present <- diseases_present %>%
            mutate(disease = coalesce(oie_listed_disease, non_oie_listed_disease)) %>%
            mutate(oie_listed = if_else(!is.na(oie_listed_disease), TRUE, 
                                        if_else(!is.na(non_oie_listed_disease), FALSE, NA))) %>%
            select(disease, everything(), -non_oie_listed_disease, -oie_listed_disease) %>%
            fill(disease, .direction = "down") %>% 
            fill(oie_listed, .direction = "down") 
        
        # get notes into table
        note_rows <- which(stri_detect_fixed(diseases_present$disease, "note", case_insensitive = TRUE))
        
        if(length(note_rows)) {
            notes <- tibble(disease = diseases_present$disease[note_rows - 1],
                            disease_row_id = 1,
                            notes = diseases_present$disease[note_rows])
            
            diseases_present <- diseases_present %>%
                group_by(disease) %>%
                mutate(disease_row_id = row_number()) %>%
                ungroup() %>%
                slice(-note_rows) %>%
                left_join(notes, by = c("disease", "disease_row_id"))  %>%
                select(-disease_row_id)
        }else{
            diseases_present$notes <- NA_character_
        }
        
    }
    
    # 2 -----------------------------------------------------------------------
    # OIE- and non-OIE-listed diseases absent 
    #TODO Add assertion that you have at least one absense or presence table--they can't both be null
    diseases_absent <- get_tables_by_index(page, 
                                           first_header_name = c("2. OIE-listed diseases absent in ", 
                                                                 "6. Non OIE-Listed diseases absent in "),
                                           second_header_name = c("3. Detailed quantitative information for OIE-listed diseases/infections present in ", 
                                                                  "7. Detailed quantitative information for non OIE-Listed diseases/infections present in "))
    
    # 3 -----------------------------------------------------------------------
    # Detailed quantitative information for OIE-listed diseases/infections present
    # Disease information by State by month
    # Get every table that has "Month" in it.  Disease names are sometimes in table header and sometime in node above.  
    
    parent <- find_parent(page, "th", "Month")
    
    if(!is.null(parent)){
        
        diseases_present_detail <- map_df(parent, function(p_node){
            disease <- html_table(p_node, fill = TRUE)[1,1] # fill needed b/c weirdness in IRQ_2015_sem0.html "/html/body/div/div[3]/div[2]/div/table[27]"
            disease_check <- str_remove(disease, "Species") %>% str_trim()
            
            # if disease name is not in header, get the node above
            if(disease_check %in% c("Wild", "Domestic")){ 
                grandparent <- xml_parent(p_node) 
                siblings <- xml_children(grandparent) 
                disease <- siblings[which(xml_path(siblings) == xml_path(p_node)) - 1] %>% html_text()
            }
            
            diseases_present_detail <-  clean_oie_report_table(list(p_node)) 
            
            assertthat::has_name(diseases_present_detail, c("month",  "new_outbreaks" )) 
            
            diseases_present_detail <- diseases_present_detail %>%
                fill(month, .direction = "down") %>%
                mutate(disease = disease) #TODO note that these output diseases do not exactly match the disease_present diseases because of line breaks
        })
        
    }else{
        diseases_present_detail <- NULL
    }
    
    # 4 -----------------------------------------------------------------------
    # Unreported OIE-listed diseases during the reporting period
    # Pulls all tables between top div marker and next section - this section has its own fromatting requirements that differ from other tbls
    #TODO Distinguish between oie-listed and non-oie-listed diseases?  relevant only to pre-2014
    
    p_title <- xml_find_all(page, "//div[contains(., \"Unreported\")]")
    p_nodeset <- p_title[5:length(p_title)]
    grandparent <- xml_parent(p_nodeset) 
    siblings <- xml_children(grandparent) 
    
    header_index <- which(siblings %in% p_nodeset)
    
    assertthat::assert_that(ifelse(report_year<2014, length(p_nodeset)==2, length(p_nodeset)==1))
    
    ifelse(length(p_nodeset)==2, next_header_name <- c("Summary on non OIE-Listed diseases/infections present", "Zoonotic diseases in humans"), 
           next_header_name <- "Zoonotic diseases in humans")
    
    next_header <- map(next_header_name, function(x){
        # try tr
        nhn <- xml_find_all(siblings, paste0('//tr[contains(., "', x,'")]')) %>% #TODO can this be td instead?
            xml_parent()
        # if doesn't work (table is empty), try div
        if(length(nhn)==0) {
            nhn <- xml_find_all(siblings, paste0('//div[contains(., "', x,'")]'))[5]
        }
        return(nhn)
    })
    
    next_header_index <- map_int(next_header, ~which(siblings %in% .))
    
    # check that there is data between headers 
    check_index <- next_header_index - header_index >1
    
    header_index <- header_index[check_index]
    next_header_index <- next_header_index[check_index]
    
    if(length(header_index)){
        all_index <- map2(header_index, next_header_index, ~(.x+1):(.y-1)) %>% reduce(c)
        parent <- siblings[all_index]
        diseases_unreported <- map_df(parent, function(p_node){
            dat <- p_node %>% 
                html_table(fill = TRUE) %>%
                t()
            tibble(taxa = unique(dat[,1]), disease = c(dat[,2:ncol(dat)])) %>% 
                filter(disease != "")
        })
    }else{
        diseases_unreported <- NULL 
    }
    
    # 5 -----------------------------------------------------------------------
    # Zoonotic diseases in humans
    parent <- find_parent(page, "td", "Zoonotic diseases in humans")
    disease_humans <- clean_oie_report_table(parent) 
    if(!is.null(disease_humans)){
        assertthat::assert_that(length(parent)==1) # only should find one match
        assertthat::has_name(disease_humans, c("no_information_available", "disease_absent")) 
    }
    
    # 6 -----------------------------------------------------------------------
    # Animal population
    parent <- find_parent(page, "td", "Animal population")
    animal_population <- clean_oie_report_table(parent) 
    if(!is.null(animal_population)){
        assertthat::assert_that(length(parent)==1) # only should find one match
        assertthat::has_name(animal_population, c("species", "production")) 
        animal_population <- animal_population %>%
            fill(species, .direction = "down")
    }
    
    # 7 -----------------------------------------------------------------------
    # Veterinarians and veterinary para-professionals
    parent <- find_parent(page, "td", "Veterinarians:")
    veterinarians <- clean_oie_report_table(parent) 
    
    if(!is.null(veterinarians)){
        assertthat::assert_that(length(parent)==1) # only should find one match
        assertthat::has_name(veterinarians, c("x", "public_sector")) 
        
        veterinarians <- veterinarians %>%
            rename(veterinarian_field = x) %>%
            mutate(veterinarian_class = "veterinarians")
        
        note <- veterinarians %>% filter(veterinarian_field == "(specify with a short note)") %>% pull(2)
        
        veterinarians <- veterinarians %>%
            mutate(veterinarian_field = ifelse(veterinarian_field=="Others", 
                                               paste0(veterinarian_field, " (", note, ")"),
                                               veterinarian_field)) %>%
            slice(-nrow(.))
        
    }
    
    parent <- find_parent(page, "td", "Veterinary Paraprofessionals")
    veterinarian_paraprofessionals <- clean_oie_report_table(parent)
    
    if(!is.null(veterinarian_paraprofessionals)){
        assertthat::assert_that(length(parent)==1) # only should find one match
        assertthat::has_name(veterinarian_paraprofessionals, c("x", "public_sector")) 
        
        veterinarian_paraprofessionals <- veterinarian_paraprofessionals %>%
            rename(veterinarian_field = x) %>%
            mutate(veterinarian_class = "veterinarian paraprofessionals")
        
        note <- veterinarian_paraprofessionals %>% filter(veterinarian_field == "(specify with a short note)") %>% pull(2)
        
        veterinarian_paraprofessionals <- veterinarian_paraprofessionals %>%
            mutate(veterinarian_field = ifelse(veterinarian_field=="Others", 
                                               paste0(veterinarian_field, " (", note, ")"),
                                               veterinarian_field)) %>%
            slice(-nrow(.))
        
    }
    veterinarians <- bind_rows(veterinarians, veterinarian_paraprofessionals)
    
    # 8 -----------------------------------------------------------------------
    #  National reference laboratories
    parent <- find_parent(page, "td", "National reference laboratories")
    national_reference_laboratories <- clean_oie_report_table(parent) 
    
    if(!is.null(national_reference_laboratories)){
        assertthat::assert_that(length(parent)==1) # only should find one match
        assertthat::has_name(national_reference_laboratories, c("name", "contacts")) 
    }
    
    # 9 -----------------------------------------------------------------------
    # Diagnostic Tests
    parent <- find_parent(page, "td", "Diagnostic Tests")
    national_reference_laboratories_detail <- clean_oie_report_table(parent)
    
    if(!is.null(national_reference_laboratories_detail)){
        assertthat::assert_that(length(parent)==1) # only should find one match
        assertthat::has_name(national_reference_laboratories_detail, c("laboratory", "disease", "test_type")) 
        
        national_reference_laboratories_detail <- national_reference_laboratories_detail %>%
            fill(laboratory, .direction = "down") %>%
            fill(disease, .direction = "down")
    }
    
    # 10 -----------------------------------------------------------------------
    # Vaccine Manufacturers
    parent <- find_parent(page, "td", "Vaccine Manufacturers")
    vaccine_manufacturers <- clean_oie_report_table(parent) 
    
    if(!is.null(vaccine_manufacturers)){
        assertthat::assert_that(length(parent)==1) # only should find one match
        assertthat::has_name(vaccine_manufacturers, c("manufacturer", "contacts")) 
    }
    
    # 11 -----------------------------------------------------------------------
    # Vaccines
    parent <- find_parent(page, "td", "Vaccines") 
    parent <- keep(parent, function(x){
        header <- xml_child(x) %>% 
            xml_text() 
        !grepl("National reference laboratories|Manufacturers|production", header)
    })
    
    #xml_nodes(page, xpath='//table/tr/td[text()="15. Vaccines"]/../..')
    #xml_nodes(page, xpath='//table/tr/td[contains(text(), "Vaccines")]/../..')
    #xml_nodes(page, xpath='//table/tr/td[contains(text(), "Vaccines")]/../..')
    
    vaccine_manufacturers_detail <- clean_oie_report_table(parent) 
    
    if(!is.null(vaccine_manufacturers_detail)){
        assertthat::assert_that(length(parent)==1) # only should find one match
        assertthat::has_name(vaccine_manufacturers_detail, c("manufacturer", "disease")) 
        
        vaccine_manufacturers_detail <- vaccine_manufacturers_detail %>%
            fill(disease, .direction = "down")
    }
    
    # 12 -----------------------------------------------------------------------
    # Vaccine production
    
    parent <- find_parent(page, "td", "Vaccine production")
    parent <- keep(parent, function(x){
        header <- xml_child(x) %>% 
            xml_text() 
        !grepl("National reference laboratories|Manufacturers|Vaccines", header)
    })
    
    vaccine_production <- clean_oie_report_table(parent) 
    
    if(!is.null(vaccine_production)){
        assertthat::assert_that(length(parent)==1) # only should find one match
        assertthat::has_name(vaccine_production, c("manufacturer", "vaccine", "doses_produced")) 
    }
    
    # output
    return(list(
        "country" = country,
        "report_months" = report_months,
        "report_year" = report_year,
        "report_period" = report_period,
        "web_page" = web_page,
        "diseases_present"= diseases_present, 
        "diseases_absent"= diseases_absent,
        "diseases_present_detail"= diseases_present_detail,
        "diseases_unreported" = diseases_unreported,
        "disease_humans" = disease_humans,
        "animal_population" = animal_population,
        "veterinarians" = veterinarians,
        "national_reference_laboratories" = national_reference_laboratories,
        "national_reference_laboratories_detail" = national_reference_laboratories_detail,
        "vaccine_manufacturers" = vaccine_manufacturers,
        "vaccine_manufacturers_detail" = vaccine_manufacturers_detail,
        "vaccine_production" = vaccine_production))
}

safe_ingest <- function(web_page) {
    out <- safely(ingest_wahis_report)(web_page)
    if(!is.null(out$result)) {
        return(out$result)
    } else {
        return(tibble(file = basename(web_page)))
    }
}

