# Support function for ingest_wahis_report
#' @param parents generated by xml_parents
#' @param country report country
#' @param report_period report period
#' @param web_page Name of the downloaded web page
#' @noRd
get_oie_report_table <- function(parents, country, report_period, web_page){
    
    tbl_out <- parents[[min(which(xml_name(parents) == "table"))]] %>% 
        html_table() %>%
        as_tibble() %>%
        set_names(.[2,]) %>%
        clean_names() %>%
        slice(-1:-2) %>%
        mutate_all(~na_if(., "")) %>%
        mutate(country = country, report_period = report_period, file = basename(web_page)) 
    
    return(tbl_out)
}

#' Extract Info from WAHIS Annual and Semi-Annual Reports
#'
#' Extract the information found in the Annual and Semi-Annual OIE World Animal Health Information
#' System (WAHIS) HTML reports. These reports have to be provided to this function.
#'
#' @param web_page Name of the downloaded web page
#'
#' @return A list with elements:
#' \item{id}{Record id.}
#' \item{diseases_present}{Table of disease present in country over time period}
#' @examples
#' ##ingest_wahis_report("../data-raw/raw_wahis_reports/BWA_2016_sem0.html")
#' @export
#' @importFrom xml2 read_xml xml_find_first xml_text xml_parents
#' @importFrom stringi stri_extract_first_regex
#' @importFrom rvest html_table
#' @importFrom purrr map_df
#' @importFrom tidyr fill
#' @importFrom magrittr set_names
#' @importFrom janitor clean_names
#' @import dplyr

ingest_wahis_report <- function(web_page) {
    
    # get page
    page <- suppressWarnings(read_xml(web_page, as_html = TRUE, options = c("RECOVER", "NOERROR", 
                                                                            "NOBLANKS")))
    # get country name
    country <- xml_find_first(page, '//td[contains(., "Country:")]') %>% xml_text() %>% stri_extract_first_regex("(?<=:\\s).*")
    
    # get report period
    report_period <- xml_find_first(page, '//td[contains(., "Report period:")]') %>% xml_text() %>% stri_extract_first_regex("(?<=:\\s).*")
    
    ## 1
    # get OIE-listed diseases/infections present
    tab_title <- xml_find_first(page, "//td[contains(., \"Summary on OIE-listed diseases/infections present in\")]")
    #if(inherits(tab_title, "xml_missing")) return(tibble(country = character(0)))
    parents <- xml_parents(tab_title)
    
    diseases_present <- get_oie_report_table(parents, country, report_period, web_page) %>%
        fill(oie_listed_disease, .direction = "down") %>% 
        group_by(oie_listed_disease) %>%
        mutate(oie_listed_disease_row_id = row_number()) %>%
        ungroup()
    
    # get notes into OIE listed disease table
    note_rows <- which(stri_detect_fixed(diseases_present$oie_listed_disease, "note", case_insensitive = TRUE))
    notes <- tibble(oie_listed_disease = diseases_present$oie_listed_disease[note_rows - 1],
                    oie_listed_disease_row_id = 1,
                    notes = diseases_present$oie_listed_disease[note_rows])
    
    if(length(note_rows)) {
        diseases_present <- diseases_present %>%
            slice(-note_rows) %>%
            left_join(notes, by = c("oie_listed_disease", "oie_listed_disease_row_id")) %>%
            select(-oie_listed_disease_row_id)
    }else{
        diseases_present$notes <- NA_character_
    }
    
    ## 2
    # get OIE-listed diseases absent
    taxa_grp <- c("Multiple species",
                  "Cattle",
                  "Sheep/Goats",
                  "Swine",
                  "Equidae",
                  "Lagomorphs",
                  "Birds",
                  "Bees",
                  "Other",
                  "Fish",
                  "Molluscs",
                  "Crustaceans")
    diseases_absent <- map_df(taxa_grp, function(tg){
        
        tbl_header_xml <- paste0('//td[contains(., "',
                                 tg,
                                 '")]')
        
        tab_title <- xml_find_first(page, tbl_header_xml)
        #if(inherits(tab_title, "xml_missing")) return(tibble(country = character(0)))
        parents <- xml_parents(tab_title)
        
        # make sure you got the absense table and not something later in the report
        out <- get_oie_report_table(parents, country, report_period, web_page) 
        if(!"date_of_last_occurrence" %in% names(out)){
            out <- tibble()
        }
        out 
    })
    
    
    return(list(
        "country" = country,
        "report_period" = report_period,
        "diseases_present"=diseases_present, 
        "diseases_absent"=diseases_absent))
}

safe_ingest <- function(web_page) {
    out <- safely(ingest_wahis_report)(web_page)
    if(!is.null(out$result)) {
        return(out$result)
    } else {
        return(tibble(file = basename(web_page)))
    }
}

