#' Download and uncompress rasters used for REPEL database
#' 
#' Target folder will be several GB large
#' 
#' Uses [furrrr::future_map()] internally so setting [future::plan()] backend
#' will allow this to run in parallel
#' 
#' @param directory where livestock data is saved
#' @import here curl furrr fs zip
#' @export
download_rasters <- function(directory = here::here("rasters")) {
    suppressWarnings(dir.create(directory, recursive = TRUE))
    sources <- list(
        "tif" = list(
            "glw_sheep" = "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/BLWPZN/P9EKFD",
            "glw_goats" = "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/OCPH42/RH3C2B",
            "glw_cattle" = "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/GIVQ75/3RYLRJ",
            "glw_ducks" = "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/ICHCBH/OPDTTP",
            "glw_chickens" = "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/SUFASB/KFY94R",
            "glw_horses" = "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/7Q52MV/NBZPIQ", 
            "glw_pigs" = "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/33N0JG/KIYWEK",
            "glw_buffaloes" = "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/5U8MWI/VN0H0L",
            "worldpop" = "https://data.worldpop.org/GIS/Population/Global_2000_2020/2020/0_Mosaicked/ppp_2020_1km_Aggregated.tif"
        ),
        "nc" =  list(
            "gdp" = "https://datadryad.org/stash/downloads/file_stream/241948"
        ),
        "zip" = list(
            "accessibility" = "https://malariaatlas.org/geoserver/ows?service=CSW&version=2.0.1&request=DirectDownload&ResourceId=Explorer:2015_accessibility_to_cities_v1.0",
            "bioclim" = "https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_5m_bio.zip"
        )
    )
    
    future_iwalk(sources, function(lst, type) {
        future_iwalk(lst, function(url, name) {
            curl_fetch_disk(url, path = path(directory,name, ext = type), handle = new_handle(followlocation = TRUE))
            if (type == "zip") {
                unzip(fs::path(directory, name, ext = type), junkpaths = TRUE, exdir = directory)
            }
        })
    })
    directory   
}

#' Define the structure of the standard raster size.
#' 
#' This is an empty raster that was generated by running `dput(raster(x))` on
#' one of the GLW rasters
#' @importClassesFrom raster RasterLayer
#' @export
raster_template <- function() {
    new("RasterLayer", file = new(".RasterFile", name = "", datanotation = "FLT4S", 
                                  byteorder = "little", nodatavalue = -Inf, NAchanged = FALSE, 
                                  nbands = 1L, bandorder = "BIL", offset = 0L, toptobottom = TRUE, 
                                  blockrows = 1L, blockcols = 4320L, driver = "", open = FALSE), 
        data = new(".SingleLayerData", values = logical(0), offset = 0, 
                   gain = 1, inmemory = FALSE, fromdisk = FALSE, isfactor = FALSE, 
                   attributes = list(), haveminmax = FALSE, min = Inf, max = -Inf, 
                   band = 1L, unit = "", names = ""), legend = new(".RasterLegend", 
                                                                   type = character(0), values = logical(0), color = logical(0), 
                                                                   names = logical(0), colortable = logical(0)), title = character(0), 
        extent = new("Extent", xmin = -180, xmax = 180, ymin = -90, 
                     ymax = 90), rotated = FALSE, rotation = new(".Rotation", 
                                                                 geotrans = numeric(0), transfun = function () 
                                                                     NULL), ncols = 4320L, nrows = 2160L, crs = new("CRS", 
                                                                                                                    projargs = "+proj=longlat +datum=WGS84 +no_defs"), history = list(), 
        z = list())
}

#' Read rasters from a directory and convert to a list of commonly-sized rasters
#' 
#' Uses [furrrr::future_map()] internally so setting [future::plan()] backend
#' will allow this to run in parallel
#' @param directory where raster data is saved
#' @param template a blank or other raster to resize the rasters to
#' @import here furrr fs stringi tools
#' @importFrom raster raster resample
#' @export
transform_rasters <- function(directory = here::here("rasters"), template = raster_template()) {
    directory = here(directory)
    raster_files <- dir_ls(path(directory), regexp = "(nc|tif)")
    raster_names = basename(tools::file_path_sans_ext(raster_files)) %>% 
        stri_replace_first_fixed("wc2.1_5m_bio", "bioclim") %>% 
        stri_replace_first_fixed("2015_accessibility_to_cities_v1.0", "accessibility")
    rasters <- future_map(raster_files, function(x) resample(raster(x), template))
    names(rasters) <- raster_names
    
    rasters
}


